### ISSUE TITLE
GET /admin/logs

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#108]
Search Parameters:

- Date from/to
- Email
- Category (admin, user, all/both)
- Fragment search (i.e., partial match/fuzzy match) in:
  - Action
  - Details

Fragment search in Action and Detail columns give more granular search control for specific changes.

Make sure to enable pagination since number of results will be significant.

**Comment by geoffturk** [comment]
Needs #90

**Comment by LIYINGZHEN** [comment]
I think this is the last step.
