### ISSUE TITLE
Validate User Permission in POST /favorites

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#116]
![image](https://user-images.githubusercontent.com/32190662/81274733-fc209a80-9050-11ea-8968-0142e490da3b.png)

A user is currently able to add a favorite to an entity not controlled by him. We need to check the user is linked to the entity where the favorite is being added. If not, return a 403 error.

**Comment by geoffturk** [comment]
@LIYINGZHEN Please resolve in #115

**Comment by maxyzli** [comment]
This should be a seperate PR.

**Comment by geoffturk** [comment]
If you prefer. Can you do it before you finish the logging PR then? Or right after?
