### ISSUE TITLE
Daily email routine crashes app

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#119]
The balance checking routine crashes the app when it is run.

**Comment by maxyzli** [comment]
@geoffturk 

It works fine on my side. Please show me the instructions to reproduce the problem.

![Screen Shot 2020-05-17 at 18 39 05](https://user-images.githubusercontent.com/11765228/82142280-b2645b00-986d-11ea-8f04-bc63b0bcb2fa.png)

**Comment by geoffturk** [comment]
Sorry, I meant the daily email routine (title updated).
