### ISSUE TITLE
Improve readability of account numbers

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#48]
The account number algorithm generates incredibly hard to read/dictate alphanumeric results. Let's replace it with an algorithm that generates results of numbers only, ideally between 12-15 digits in length.

It would be good to add a checksum algorithm such as the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm) so users get immediate feedback if they type (or paste) an incorrect (or incomplete) account number.

This is a usability improvement. **3746 4609 0019 3732** is a lot nicer than **1YaZwmxPpT7BxHI5fNVhVzUJo24**. 😱

**Comment by maxyzli** [comment]
Is there any library we can use?

----------

Package found：

1. https://github.com/ShiraazMoollatjie/goluhn

**Comment by geoffturk** [comment]
Looks good. Let's generate 15 digit numbers  so the checksum makes 16. Grouping them in blocks  of four makes them easy to read.
