### ISSUE TITLE
GET/PATCH  /admin/users/{userID}

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#94]

**Comment by geoffturk** [comment]
### GET

Get details of a specific user by ID.

- All user details, plus:
- List of linked entities by entity ID

**Comment by geoffturk** [comment]
### PATCH

Update a user's details.

- First name
- Last name
- Email
- Telephone
- Password
- Email notifications flag
- Show tags matched since last login flag
- Linked entities (an array that is updated like the offers/wants arrays; need to include all entity IDs that will be included in the array)

**Comment by maxyzli** [comment]
`Patch: Linked entities` is very tricky.

I have to not only update the user but also all the affected entities. 

Some of the entities need to remove the user form it and some of them need to add the user.

**Comment by geoffturk** [comment]
> Some of the entities need to remove the user form it and some of them need to add the user.

OK. 

Short term (i.e., when we work on `PATCH /admin/entities/{entityID`}) - We will want to be able to do it from the entity side as well: some of the users need to remove the entity from it while others need the entity added to their user records.

Long term - Once roles are in place, admin users of entities should be able to add/remove users from an entity they are an admin of. Also, users should be able to leave an entity (i.e., disassociate the entity from their user record).

**Comment by geoffturk** [comment]
Also, we should add a DELETE endpoint as well. I'm not sure what the restrictions should be for now but there should probably be two types of deleting:
1) Marking the user record as deleted with a date/time stamp, but leaving the record in the DB
2) Completely deleting the record

No. 2 is useful to clean the DB if a bunch of garbage accounts are created, either by accident or maliciously.

**Comment by geoffturk** [comment]
Closed by #95
