### ISSUE TITLE
DELETE /admin/users/{userID}

### ISSUE THREAD

**Issue by geoffturk** [ic3network/mccs-alpha-api#96]
There needs to be a DELETE endpoint as well. I'm not sure what the restrictions should be for now but there ought to be two types of deleting:

1. Marking the user record as deleted with a date/time stamp, but leaving the record in the DB
2. Completely deleting the record

No. 2 is useful to clean the DB if a bunch of garbage accounts are created, either by accident or maliciously.

**Comment by maxyzli** [comment]
Let's try 1 first. We can write a script to delete garbage accounts if needed.
